.dashPager_js_metadata <- function() {
deps_metadata <- list(`dash_pager` = structure(list(name = "dash_pager",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Pager.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashPager",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_pager` = structure(list(name = "dash_pager",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Pager.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashPager",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_pager` = structure(list(name = "dash_pager",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_pager.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashPager",
all_files = FALSE), class = "html_dependency"),
`dash_pager` = structure(list(name = "dash_pager",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_pager.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashPager",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
